#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Razordex
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class PokemonHTMLView : PokemonHTMLViewBase
{

#line hidden

#line 2 "/Users/segphault/Dropbox/Projects/Tests/Mono/Razordex/Razordex/PokemonHTMLView.cshtml"
public Pokemon Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("\n");

WriteLiteral("<html>\n<head>\n\t<link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"style.css\"");

WriteLiteral(" />\n</head>\n<body>\n\n\t<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">Type</div>\n\t\t<table");

WriteLiteral(" class=\"data\"");

WriteLiteral(">\n\t\t\t<tr><td><b>Primary:</b></td><td>");


#line 13 "/Users/segphault/Dropbox/Projects/Tests/Mono/Razordex/Razordex/PokemonHTMLView.cshtml"
                              Write(Model.primary_type);


#line default
#line hidden
WriteLiteral("</td></tr>\n\t\t\t<tr><td><b>Secondary:</b></td><td>");


#line 14 "/Users/segphault/Dropbox/Projects/Tests/Mono/Razordex/Razordex/PokemonHTMLView.cshtml"
                                Write(Model.secondary_type);


#line default
#line hidden
WriteLiteral("</td></tr>\n\t\t</table>\n\t</div>\n\t\n\t<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">Ability</div>\n\t\t<table");

WriteLiteral(" class=\"data\"");

WriteLiteral(">\n\t\t\t<tr><td><b>Primary:</b></td><td>");


#line 21 "/Users/segphault/Dropbox/Projects/Tests/Mono/Razordex/Razordex/PokemonHTMLView.cshtml"
                              Write(Model.primary_ability);


#line default
#line hidden
WriteLiteral("</td></tr>\n\t\t\t<tr><td><b>Secondary:</b></td><td>");


#line 22 "/Users/segphault/Dropbox/Projects/Tests/Mono/Razordex/Razordex/PokemonHTMLView.cshtml"
                                Write(Model.secondary_ability);


#line default
#line hidden
WriteLiteral("</td></tr>\n\t\t</table>\n\t</div>\n\n\t<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n\t\t<div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">Description</div>\n\t\t<div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">");


#line 28 "/Users/segphault/Dropbox/Projects/Tests/Mono/Razordex/Razordex/PokemonHTMLView.cshtml"
                  Write(Model.biography);


#line default
#line hidden
WriteLiteral("</div>\n\t</div>\n\n</body>\n</html>");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class PokemonHTMLViewBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		///<summary>Executes the template and returns the output as a string.</summary>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		///<summary>Executes the template, writing to the provided text writer.</summary>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		///<summary>Writes literal values to the template output without HTML escaping them.</summary>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		///<summary>Writes values to the template output, HTML escaping them if necessary.</summary>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template uses any Razor helpers, but you may choose to implement it differently
		//
		///<summary>Invokes the action to write directly to the template output.</summary>
		///<remarks>This is used for Razor helpers, which already perform any necessary HTML escaping.</remarks>
		protected void Write (Action<System.IO.TextWriter> write)
		{
			write (__razor_writer);
		}

		// This method is REQUIRED if the template has any Razor helpers, but you may choose to implement it differently
		//
		///<remarks>Used by Razor helpers to HTML escape values.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value != null) {
				writer.Write (System.Web.HttpUtility.HtmlEncode (value.ToString ()));
				// NOTE: better version for .NET 4+, handles pre-escape HTML (IHtmlString)
				// writer.Write (System.Web.HttpUtility.HtmlEncode (value));
			}
		}

		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
